import type { Metadata } from 'next';

import { Toaster } from '@/components/ui/sonner';

import NotificationsTest from './components/NotificationsTest';
import { ThemeBody } from './components/ThemeBody';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeBody>
        <NotificationsTest />
        {children}
        <Toaster duration={5000} />
      </ThemeBody>
    </html>
  );
}
